dist: trusty
language: python
python:
  - "2.7"

sudo: false

install:
 - travis_retry pip install --upgrade pip
 - travis_retry pip install --upgrade six
 - travis_retry pip install --upgrade pyflakes
 - travis_retry pip install -r client/requirements.txt

script:
 - PATH="${HOME}/.local/bin:${PATH}" python lint.py
 - PYTHONPATH="client:${PYTHONPATH}" python test_runner.py `find client/test/test_*.py | xargs`
